name: indic_voice_food
description: "Indic Voice-to-UI Food Delivery Clone powered by Sarvam AI"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true